#4
resources:
- name: terraform-resources
  type: git
  source:
    uri: https://github.com/PrathibaVasu/concourse-repo.git
    branch: tn  


- name: terraform-image
  type: git
  source:
    uri: https://github.com/hashicorp/docker-hub-images.git
    branch: master


jobs:
  - name: terraform-pipe-line
    plan:
    - get: terraform-image
    - get: terraform-resources
      trigger: true


    - task: check-terrafom-version
      config:
        platform: linux
        image_resource:
          type: docker-image
          source: {repository: hashicorp/terraform}
        run:
            path: sh
            args: 
                - -exc
                - |
                  terraform --version

    - task: plan-terraform
      config:
        platform: linux
        image_resource:
          type: docker-image
          source: {repository: hashicorp/terraform}
        inputs:
            - name: terraform-resources        
        run:
            path: sh
            args: 
                - -exc
                - |
                  env
                  ls -lrth
                  cd terraform-resources/
                  mkdir ./terraform/temp 
                  find ./terraform -name '*.tf*' -exec cp {} ./terraform/temp/ \;
                  cp -r ./terraform ./terraform/temp 
                  cd ./terraform/temp
                  ls -lrth                  
                  terraform init 
                  terraform plan


    - task: run-terraform
      input_mapping: { infra-repo: terraform-resources }    
      config:
        platform: linux
        image_resource:
          type: docker-image
          source: {repository: hashicorp/terraform}
        inputs: [{ name: infra-repo }]
        run: { path: infra-repo/terraform/config/terraform_create.sh }
